/*性別分層*/
proc phreg data=g.lag0sex1;
model time*event(0)= r_10 o3_10 nox_10 sox_10 t rh_10 /risklimits;
strata ke;ods output parameterestimates=pp;
ods listing close;
ods pdf file="I:\2 USER\SAS匯出資料\統計\病例交叉\0529\com\把有缺值的數據刪掉\n_LAG0sex1.pdf";
proc print data=pp;
run;
ods pdf close;
ode listing;
proc phreg data=g.lag0sex2;
model time*event(0)= r_10 o3_10 nox_10 sox_10 t rh_10 /risklimits;
strata ke;ods output parameterestimates=pp;
ods listing close;
ods pdf file="I:\2 USER\SAS匯出資料\統計\病例交叉\0529\com\把有缺值的數據刪掉\n_LAG0sex2.pdf";
proc print data=pp;
run;
ods pdf close;
ode listing;



/*age分層*/
proc phreg data=g.lag0age04;
model time*event(0)= r_10 o3_10 nox_10 sox_10 t rh_10 /risklimits;
strata ke;ods output parameterestimates=pp;
ods listing close;
ods pdf file="I:\2 USER\SAS匯出資料\統計\病例交叉\0529\com\把有缺值的數據刪掉\n_LAG0age04.pdf";
proc print data=pp;
run;
ods pdf close;
ode listing;
proc phreg data=g.lag0age59;
model time*event(0)= r_10 o3_10 nox_10 sox_10 t rh_10 /risklimits;
strata ke;ods output parameterestimates=pp;
ods listing close;
ods pdf file="I:\2 USER\SAS匯出資料\統計\病例交叉\0529\com\把有缺值的數據刪掉\n_LAG0age59.pdf";
proc print data=pp;
run;
ods pdf close;
ode listing;
proc phreg data=g.lag0age10;
model time*event(0)= r_10 o3_10 nox_10 sox_10 t rh_10 /risklimits;
strata ke;ods output parameterestimates=pp;
ods listing close;
ods pdf file="I:\2 USER\SAS匯出資料\統計\病例交叉\0529\com\把有缺值的數據刪掉\n_LAG0age10.pdf";
proc print data=pp;
run;
ods pdf close;
ode listing;

/*location*/
proc phreg data=g.lag0lon;
model time*event(0)= r_10 o3_10 nox_10 sox_10 t rh_10 /risklimits;
strata ke;ods output parameterestimates=pp;
ods listing close;
ods pdf file="I:\2 USER\SAS匯出資料\統計\病例交叉\0529\com\把有缺值的數據刪掉\n_LAG0lon.pdf";
proc print data=pp;
run;
ods pdf close;
ode listing;
proc phreg data=g.lag0loc;
model time*event(0)= r_10 o3_10 nox_10 sox_10 t rh_10 /risklimits;
strata ke;ods output parameterestimates=pp;
ods listing close;
ods pdf file="I:\2 USER\SAS匯出資料\統計\病例交叉\0529\com\把有缺值的數據刪掉\n_LAGloc.pdf";
proc print data=pp;
run;
ods pdf close;
ode listing;
proc phreg data=g.lag0los;
model time*event(0)= r_10 o3_10 nox_10 sox_10 t rh_10 /risklimits;
strata ke;ods output parameterestimates=pp;
ods listing close;
ods pdf file="I:\2 USER\SAS匯出資料\統計\病例交叉\0529\com\把有缺值的數據刪掉\n_LAG0los.pdf";
proc print data=pp;
run;
ods pdf close;
ode listing;
proc phreg data=g.lag0loe;
model time*event(0)= r_10 o3_10 nox_10 sox_10 t rh_10 /risklimits;
strata ke;ods output parameterestimates=pp;
ods listing close;
ods pdf file="I:\2 USER\SAS匯出資料\統計\病例交叉\0529\com\把有缺值的數據刪掉\n_LAG0loe.pdf";
proc print data=pp;
run;
ods pdf close;
ode listing;

/*season*/
proc phreg data=g.lag0sew;
model time*event(0)= r_10 o3_10 nox_10 sox_10 t rh_10 /risklimits;
strata ke;ods output parameterestimates=pp;
ods listing close;
ods pdf file="I:\2 USER\SAS匯出資料\統計\病例交叉\0529\com\把有缺值的數據刪掉\n_LAG0sew.pdf";
proc print data=pp;
run;
ods pdf close;
ode listing;
proc phreg data=g.lag0sesp;
model time*event(0)= r_10 o3_10 nox_10 sox_10 t rh_10 /risklimits;
strata ke;ods output parameterestimates=pp;
ods listing close;
ods pdf file="I:\2 USER\SAS匯出資料\統計\病例交叉\0529\com\把有缺值的數據刪掉\n_LAG0sesp.pdf";
proc print data=pp;
run;
ods pdf close;
ode listing;
proc phreg data=g.lag0sesu;
model time*event(0)= r_10 o3_10 nox_10 sox_10 t rh_10 /risklimits;
strata ke;ods output parameterestimates=pp;
ods listing close;
ods pdf file="I:\2 USER\SAS匯出資料\統計\病例交叉\0529\com\把有缺值的數據刪掉\n_LAG0sesu.pdf";
proc print data=pp;
run;
ods pdf close;
ode listing;
proc phreg data=g.lag0seau;
model time*event(0)= r_10 o3_10 nox_10 sox_10 t rh_10 /risklimits;
strata ke;ods output parameterestimates=pp;
ods listing close;
ods pdf file="I:\2 USER\SAS匯出資料\統計\病例交叉\0529\com\把有缺值的數據刪掉\n_LAG0seau.pdf";
proc print data=pp;
run;
ods pdf close;
ode listing;
